export enum ProductosEvent {
    CREATE_PRODUCTO = "CREATE_PRODUCTO",
    UPDATE_PRODUCTO = "UPDATE_PRODUCTO",
    DELETE_PRODUCTO = "DELETE_PRODUCTO",
    GET_PRODUCTO = "GET_PRODUCTO",
    GET_PRODUCTOS = "GET_PRODUCTOS",
}