export enum UsuariosEvent {
    CREATE_USUARIO = "CREATE_USUARIO",
    UPDATE_USUARIO = "UPDATE_USUARIO",
    DELETE_USUARIO = "DELETE_USUARIO",
    GET_USUARIO = "GET_USUARIO",
    GET_USUARIOS = "GET_USUARIOS",
}