export enum VentasEvent {
    CREATE_VENTAS = "CREATE_VENTAS",
    UPDATE_VENTAS = "UPDATE_VENTAS",
    DELETE_VENTAS = "DELETE_VENTAS",
    GET_VENTAS = "GET_VENTAS",
    GET_VENTASS = "GET_VENTASS",
}